package com.gft.hellotestrobobar;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class RobobarSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeAll
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterAll
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void oneAllLess18() {
    driver.get("http://localhost:3000/#!/");
    driver.manage().window().setSize(new Dimension(1097, 961));
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("ageInput")).click();
    driver.findElement(By.id("ageInput")).sendKeys("17");
    driver.findElement(By.cssSelector(".btn-success")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".btn-default")).click();
  }
  @Test
  public void oneAllMore18() {
    driver.get("http://localhost:3000/#!/");
    driver.manage().window().setSize(new Dimension(1097, 961));
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("ageInput")).click();
    driver.findElement(By.id("ageInput")).sendKeys("19");
    driver.findElement(By.cssSelector(".btn-success")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("New order")).click();
  }
  @Test
  public void oneBeerLess18() {
    driver.get("http://localhost:3000/#!/");
    driver.manage().window().setSize(new Dimension(1097, 961));
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("ageInput")).click();
    driver.findElement(By.id("ageInput")).sendKeys("17");
    driver.findElement(By.cssSelector(".btn-success")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
  @Test
  public void oneBeerMore18() {
    driver.get("http://localhost:3000/#!/");
    driver.manage().window().setSize(new Dimension(1097, 961));
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("ageInput")).click();
    driver.findElement(By.id("ageInput")).sendKeys("20");
    driver.findElement(By.cssSelector(".btn-success")).click();
  }
  @Test
  public void oneWineMore18() {
    driver.get("http://localhost:3000/#!/");
    driver.manage().window().setSize(new Dimension(1097, 961));
    driver.findElement(By.cssSelector(".ng-scope:nth-child(3) .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("ageInput")).click();
    driver.findElement(By.id("ageInput")).sendKeys("17");
    driver.findElement(By.cssSelector(".btn-success")).click();
  }
  @Test
  public void twoColasTwoBeersMore18() {
    driver.get("http://localhost:3000/#!/");
    driver.manage().window().setSize(new Dimension(1097, 961));
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .input-group-append > .btn"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .input-group-append > .btn"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("ageInput")).click();
    driver.findElement(By.id("ageInput")).sendKeys("19");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.close();
  }
}
